# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PW'] %>
  host:     <%= ENV['MYSQL_HOST'] %>
  timeout:  5000

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV['TEST_DATABASE_NAME'] %>
  username: <%= ENV['TEST_MYSQL_USER'] %>
  password: <%= ENV['TEST_MYSQL_PW'] %>
  host:     <%= ENV['TEST_MYSQL_HOST'] %>

production:
  <<: *default
