# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  smtp_address: <%= ENV['SMTP_SERVER'] %>
  smtp_port: <%= ENV['SMTP_PORT'].to_i %>
  smtp_domain: <%= ENV['SMTP_DOMAIN'] %>
  smtp_user_name: <%= ENV['SMTP_USER'] %>
  smtp_password: <%= ENV['SMTP_PASSWORD'] %>
  secret_key_base: 302119ab88dd2e699bab093d48ebfe4fcae911d1ad7655ce025923453d4cd1dd2b548c31124e7e4f37a324074981d95e432fee2287856a0c4d1cbe406594c159

test:
  secret_key_base: a7e322dbf527fb8f4a123f4a690edc50bad2f5ffaabce18aff4425ecdac61e30427df7ef792e7f3faa41a2593b622e8468893ebb094fbd54910e1d1936f47765

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  smtp_address:    <%= ENV['SMTP_SERVER'] %>
  smtp_port:       <%= ENV['SMTP_PORT'].to_i %>
  smtp_domain:     <%= ENV['SMTP_DOMAIN'] %>
  smtp_user_name:  <%= ENV['SMTP_USER'] %>
  smtp_password:   <%= ENV['SMTP_PASSWORD'] %>
  ga_track_id:     <%= ENV['GA_TRACK_ID'] %>
