# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  smtp_address: <%= ENV['SMTP_SERVER'] %>
  smtp_port: <%= ENV['SMTP_PORT'].to_i %>
  smtp_domain: <%= ENV['SMTP_DOMAIN'] %>
  smtp_user_name: <%= ENV['SMTP_USER'] %>
  smtp_password: <%= ENV['SMTP_PASSWORD'] %>
  secret_key_base: 7da80763270c058bfff6a54539c697b8630dab81e24d3733f590d7d163d4e16dccc969f171ff13d950cf43e8ebade350317f8902fec9bbc879e50cce019f95c8


test:
  secret_key_base: 6b73f365b4fe2ab2159444ab263e12316b1a124421a8a78ff11496b13c16e8521ac5abaf8054bbd393601bd1907e2b4ba824e915b4234ed6c06c2941967c3947

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  smtp_address:    <%= ENV['SMTP_SERVER'] %>
  smtp_port:       <%= ENV['SMTP_PORT'].to_i %>
  smtp_domain:     <%= ENV['SMTP_DOMAIN'] %>
  smtp_user_name:  <%= ENV['SMTP_USER'] %>
  smtp_password:   <%= ENV['SMTP_PASSWORD'] %>
  ga_track_id:     <%= ENV['GA_TRACK_ID'] %>
